import type { Metadata } from "next";
import { sourceCodePro } from "./ui/fonts";
import "./ui/globals.css";

export const metadata: Metadata = {
  title: "Connor Pepin Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <link rel="icon" href="/catCrunch.png" />
      <body className={sourceCodePro.className}>{children}</body>
    </html>
  );
}
